const products = [
  {
    type: 'Room Spray',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-1.png',
    btn: 'QUICK SHOP',
    category: 'BESTSELLER',
    isBestseller: true,
  },
  {
    type: 'Scented Candle',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-2.png',
    btn: 'QUICK SHOP',
    category: 'BESTSELLER',
    isBestseller: true,
  },
  {
    type: 'Compact diffuser',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-3.png',
    btn: 'QUICK SHOP',
    category: 'BESTSELLER',
    isBestseller: true,
  },

  {
    type: 'Scented Candle',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-2.png',
    btn: 'QUICK SHOP',
    category: 'LIVINGROOM',
    isBestseller: false,
  },
  {
    type: 'Scented Candle',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-2.png',
    btn: 'QUICK SHOP',
    category: 'LIVINGROOM',
  },
  {
    type: 'Scented Candle',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-2.png',
    btn: 'QUICK SHOP',
    category: 'LIVINGROOM',
  },

  {
    type: 'Room Spray',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-1.png',
    btn: 'QUICK SHOP',
    category: 'BATHROOM',
  },
  {
    type: 'Room Spray',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-1.png',
    btn: 'QUICK SHOP',
    category: 'BATHROOM',
  },
  {
    type: 'Room Spray',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-1.png',
    btn: 'QUICK SHOP',
    category: 'BATHROOM',
  },

  {
    type: 'Compact diffuser',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-3.png',
    btn: 'QUICK SHOP',
    category: 'WARDROBE',
  },
  {
    type: 'Compact diffuser',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-3.png',
    btn: 'QUICK SHOP',
    category: 'WARDROBE',
  },
  {
    type: 'Compact diffuser',
    price: '120$',
    name: 'Mayfair Affair',
    url: './images/product1.png',
    urlDesktop: './images/imgs/desktop/bestseller-desktop-3.png',
    btn: 'QUICK SHOP',
    category: 'WARDROBE',
  },
];

export default products;
